<a href="https://colab.research.google.com/github/AAAAlanHe/DSC110/blob/main/week%208.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Prep for Machine Learning Prediction

In [ ]:
#import pandas
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [ ]:
#Read the CSV file
df = pd.read_csv('https://raw.githubusercontent.com/osoliman/DSC110/refs/heads/main/Datasets/nhanes_final.csv')

In [ ]:
#check data
df.head()

,id,gender,age,race_ethnicity,education,bmi,height_cm,systolic_bp,has_diabetes,hba1c,fasting_glucose
0,130378.0,1.0,43.0,6.0,5.0,27.0,179.5,135.0,2.0,5.6,113.0
1,130379.0,1.0,66.0,3.0,5.0,33.5,174.2,121.0,2.0,5.6,99.0
2,130380.0,2.0,44.0,2.0,3.0,29.7,152.9,111.0,1.0,6.2,156.0
3,130381.0,2.0,5.0,7.0,NaN,23.8,120.1,NaN,2.0,NaN,NaN
4,130382.0,1.0,2.0,3.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN

# Filtering

In [ ]:
#filter the group of age>= 18
df = df[df['age'] >= 18].copy()

In [ ]:
#the minimun age in that group is 18
df['age'].min()

18.0

In [ ]:
df.shape

(8153, 11)

# Dropping Coloums

In [ ]:
#drop three coloums
df = df.drop(columns=['id', 'hba1c', 'fasting_glucose'])

In [ ]:
#number of colums get 3 less after dropping
df.shape

(8153, 8)

In [ ]:
#the table after dropping
df.head()

,gender,age,race_ethnicity,education,bmi,height_cm,systolic_bp,has_diabetes
0,1.0,43.0,6.0,5.0,27.0,179.5,135.0,2.0
1,1.0,66.0,3.0,5.0,33.5,174.2,121.0,2.0
2,2.0,44.0,2.0,3.0,29.7,152.9,111.0,1.0
6,1.0,43.0,1.0,2.0,NaN,NaN,NaN,2.0
7,2.0,65.0,3.0,3.0,NaN,NaN,NaN,2.0

# Label Mapping

In [ ]:
gender_map = {1.0: 'Male', 2.0: 'Female'}
race_map = {1.0: 'Mexican American',
       2.0: 'Other Hispanic',
       3.0: 'White',
       4.0: 'Black',
       6.0: 'Asian',
       7.0: 'Other'}
education_map ={1.0: 'Less than 9th',
         2.0: '9-11th grade',
         3.0: 'High school',
         4.0: 'Some college',
         5.0: 'College grad',
         9.0: 'Do not know'}

In [ ]:
#label gender
df['gender'] = df['gender'].map(gender_map)

In [ ]:
df.head()

,gender,age,race_ethnicity,education,bmi,height_cm,systolic_bp,has_diabetes
0,NaN,43.0,Asian,College grad,27.0,179.5,135.0,2.0
1,NaN,66.0,White,College grad,33.5,174.2,121.0,2.0
2,NaN,44.0,Other Hispanic,High school,29.7,152.9,111.0,1.0
6,NaN,43.0,Mexican American,9-11th grade,NaN,NaN,NaN,2.0
7,NaN,65.0,White,High school,NaN,NaN,NaN,2.0

In [ ]:
#label race_ethnicity
df['race_ethnicity'] = df['race_ethnicity'].map(race_map)

In [ ]:
df['race_ethnicity'].head()

0    NaN
1    NaN
2    NaN
6    NaN
7    NaN
Name: race_ethnicity, dtype: object

In [ ]:
#label education
df['education'] = df['education'].map(education_map)

In [ ]:
df['education'].head()

0    NaN
1    NaN
2    NaN
6    NaN
7    NaN
Name: education, dtype: object

# Missing values

In [ ]:
df.isna().sum()

gender            8153
age                  0
race_ethnicity    8153
education         8153
bmi               1918
height_cm         1891
systolic_bp       2030
has_diabetes         3
dtype: int64

In [ ]:
#Missing values imputation
df['bmi']         = df['bmi'].fillna(df['bmi'].mean())
df['height_cm']   = df['height_cm'].fillna(df['height_cm'].mean())
df['systolic_bp'] = df['systolic_bp'].fillna(df['systolic_bp'].mean())

In [ ]:
#Missing values removal
df = df.dropna(subset=['education']).copy()

In [ ]:
#Missing values check
df.isna().sum()

gender            0
age               0
race_ethnicity    0
education         0
bmi               0
height_cm         0
systolic_bp       0
has_diabetes      0
dtype: int64

# Defining target variable

In [ ]:
df = df[df['has_diabetes'].isin([1.0, 2.0])].copy()

In [ ]:
#target is has_diabete
df['has_diabetes'] = df['has_diabetes'].map({1.0: 1, 2.0: 0})

In [ ]:
df.shape

(0, 8)

# One-Hot Encodeing

In [ ]:
df = pd.get_dummies(df, columns=['gender', 'race_ethnicity', 'education'],drop_first=True)

# Scaling numeric variables

In [ ]:
numeric_cols = ['age', 'bmi', 'height_cm', 'systolic_bp']
scaler = StandardScaler()
df[numeric_cols] = scaler.fit_transform(df[numeric_cols])
#verifying

# Train-test split

In [ ]:
X = df.drop(columns=['has_diabetes'])
y = df['has_diabetes']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)