<a href="https://colab.research.google.com/github/AAAAlanHe/DSC110/blob/main/week%205.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
# import data
df = pd.read_csv('https://raw.githubusercontent.com/osoliman/DSC110/refs/heads/main/Datasets/nhanes_final.csv')

In [12]:
#show top 10 rows
df.head(10)

,id,gender,age,race_ethnicity,education,bmi,height_cm,systolic_bp,has_diabetes,hba1c,fasting_glucose
0,130378.0,1.0,43.0,6.0,5.0,27.0,179.5,135.0,2.0,5.6,113.0
1,130379.0,1.0,66.0,3.0,5.0,33.5,174.2,121.0,2.0,5.6,99.0
2,130380.0,2.0,44.0,2.0,3.0,29.7,152.9,111.0,1.0,6.2,156.0
3,130381.0,2.0,5.0,7.0,NaN,23.8,120.1,NaN,2.0,NaN,NaN
4,130382.0,1.0,2.0,3.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN
5,130383.0,2.0,3.0,2.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN
6,130384.0,1.0,43.0,1.0,2.0,NaN,NaN,NaN,2.0,NaN,NaN
7,130385.0,2.0,65.0,3.0,3.0,NaN,NaN,NaN,2.0,NaN,NaN
8,130386.0,1.0,34.0,1.0,4.0,30.2,173.3,110.0,2.0,5.1,100.0
9,130387.0,2.0,68.0,3.0,5.0,42.6,155.9,143.0,2.0,5.9,NaN

In [11]:
#show last 1 rows
df.tail(1)

,id,gender,age,race_ethnicity,education,bmi,height_cm,systolic_bp,has_diabetes,hba1c,fasting_glucose
11932,142310.0,2.0,80.0,3.0,3.0,27.6,161.7,128.0,2.0,5.3,NaN

In [13]:
#number of lines and rows
df.shape

(11933, 11)

In [15]:
#first digit of shape
df.shape[0]

11933

In [30]:
print(f"The number of rows in our dataframe is {df.shape[0]} rows")

The number of rows in our dataframe is 11933 rows

In [31]:
print(f"The number of lines in our dataframe is {df.shape[1]} lines")

The number of lines in our dataframe is 11 lines

In [43]:
#Boolean
1+1==3

False

In [44]:
1+1==2

True

In [37]:
int(True)

1

In [39]:
int(False)

0

# data cleaning

In [46]:
#where is the comment
df.isna().sum()

id                    0
gender                0
age                   0
race_ethnicity        0
education          4139
bmi                3462
height_cm          3434
systolic_bp        4416
has_diabetes        193
hba1c              5218
fasting_glucose    8261
dtype: int64

In [54]:
df.isna().mean() *100

id                  0.000000
gender              0.000000
age                 0.000000
race_ethnicity      0.000000
education          34.685326
bmi                29.011984
height_cm          28.777340
systolic_bp        37.006620
has_diabetes        1.617364
hba1c              43.727478
fasting_glucose    69.228191
dtype: float64

In [55]:
# Drop rows where has_diabetes is missing
df_clean = df.dropna(subset=['has_diabetes']).copy()

In [56]:
df_clean.isna().mean() *100

id                  0.000000
gender              0.000000
age                 0.000000
race_ethnicity      0.000000
education          33.611584
bmi                27.844974
height_cm          27.606474
systolic_bp        35.971039
has_diabetes        0.000000
hba1c              42.802385
fasting_glucose    68.722317
dtype: float64

In [57]:
df_clean.shape

(11740, 11)

In [61]:
#Fill missing systolic_bp with mean
mean_bp = df_clean['systolic_bp'].mean()
print(mean_bp)

119.28854596248502

In [62]:
df_clean['systolic_bp'] = df_clean['systolic_bp'].fillna(mean_bp)

In [63]:
# Check it worked - should be 0 now
df_clean['systolic_bp'].isna().sum()

np.int64(0)

# Transform variables

In [64]:
#converting numerical to categorical
# Create BMI categories
df['bmi_category'] = pd.cut(df['bmi'],
                             bins=[0, 18.5, 25, 30, 100],
                             labels=['Underweight', 'Normal', 'Overweight', 'Obese'])

In [65]:
# Check it worked
df['bmi_category'].value_counts()

bmi_category
Obese          2666
Normal         2400
Overweight     2189
Underweight    1216
Name: count, dtype: int64

# Categorical Variables transformation

In [67]:
df['education'].head()

0    5.0
1    5.0
2    3.0
3    NaN
4    NaN
Name: education, dtype: float64

In [80]:
# Create a mapping dictionary (adjust based on your data dictionary)
education_map = {
    1: 'Less than 9th grade',
    2: '9-11th grade',
    3: 'High school grad',
    4: 'Some college or AA degree',
    5: 'College graduate',
    9: 'Do not know',
    None: 'Missing'
}

In [81]:
education_map[1]

'Less than 9th grade'

In [83]:
# Apply the mapping
df['education_label'] = df['education'].map(education_map)

In [84]:
# Check it worked
df['education_label'].value_counts()

education_label
Missing                      4139
College graduate             2625
Some college or AA degree    2370
High school grad             1749
9-11th grade                  666
Less than 9th grade           373
Do not know                    11
Name: count, dtype: int64

# Data Summarization

In [89]:
# Median
df['age'].median()
print(f"The average age of our data is round {df['age'].median()}")

The average age of our data is round 37.0

In [90]:
# standard deviation
df['age'].std()
print(f"The standard deviation of age of our data is round {df['age'].std()}")

The standard deviation of age of our data is round 25.60199011389104

In [91]:
# IQR - just the 25th and 75th percentiles
df['age'].quantile([0.25, 0.75])

0.25    13.0
0.75    62.0
Name: age, dtype: float64

In [92]:
df['age'].mode()

0    80.0
Name: age, dtype: float64

In [93]:
# Simple counts
df['education_label'].value_counts()

education_label
Missing                      4139
College graduate             2625
Some college or AA degree    2370
High school grad             1749
9-11th grade                  666
Less than 9th grade           373
Do not know                    11
Name: count, dtype: int64

In [94]:
# With percentages
df['education_label'].value_counts(normalize=True) * 100

education_label
Missing                      34.685326
College graduate             21.997821
Some college or AA degree    19.860890
High school grad             14.656834
9-11th grade                  5.581161
Less than 9th grade           3.125786
Do not know                   0.092181
Name: proportion, dtype: float64

In [95]:
# Create cross-tabulation
pd.crosstab(df['has_diabetes'], df['bmi_category'])

bmi_category  Underweight  Normal  Overweight  Obese
has_diabetes
1.0                     4     109         233    504
2.0                  1211    2251        1886   2042
3.0                     0      39          70    120
9.0                     1       1           0      0

In [96]:
# With row percentages (more useful clinically)
pd.crosstab(df['has_diabetes'], df['bmi_category'], normalize='index') * 100

bmi_category  Underweight     Normal  Overweight      Obese
has_diabetes
1.0              0.470588  12.823529   27.411765  59.294118
2.0             16.387009  30.460081   25.520974  27.631935
3.0              0.000000  17.030568   30.567686  52.401747
9.0             50.000000  50.000000    0.000000   0.000000

In [97]:
#df.groupby('grouping_variable')['numeric_variable'].calculation()
df.groupby('has_diabetes')['bmi'].mean()

has_diabetes
1.0    32.981412
2.0    26.439797
3.0    32.068559
9.0    19.250000
Name: bmi, dtype: float64